

const Constant = {
    DISPLAY: {
        INIT_WIDTH: 500,
        INIT_HEIGHT: 500,
        MIN_WIDTH: 50,
        MIN_HEIGHT: 50,
        MAX_WIDTH: 3000,
        MAX_HEIGHT: 3000,
    },
    CONTAINER: {
        INIT_WIDTH: 100,
        INIT_HEIGHT: 170,
        INIT_LEFT: 30,
        INIT_TOP: 30,
        BORDER_COLOR: "black",
        BORDER_RADIUS: "1",
        BORDER_THICK: "1",
        FONT_SIZE: "7",
        BACKGROUND_COLOR: "white",
        PROPERTY: "Container",
    },
    LABEL: {
        INIT_WIDTH: 60,
        INIT_HEIGHT: 30,
        INIT_LEFT: 30,
        INIT_TOP: 30,
        BORDER_COLOR: "black",
        BORDER_RADIUS: "1",
        BORDER_THICK: "1",
        FONT_SIZE: "7",
        BACKGROUND_COLOR: "white",
        PROPERTY: "Label",
    },
    BUTTON: {
        INIT_WIDTH: 60,
        INIT_HEIGHT: 30,
        INIT_LEFT: 30,
        INIT_TOP: 30,
        BORDER_COLOR: "black",
        BORDER_RADIUS: "1",
        BORDER_THICK: "1",
        FONT_SIZE: "7",
        BACKGROUND_COLOR: "white",
        PROPERTY: "Button",
    },
    INPUT: {
        INIT_WIDTH: 60,
        INIT_HEIGHT: 30,
        INIT_LEFT: 30,
        INIT_TOP: 30,
        BORDER_COLOR: "black",
        BORDER_RADIUS: "1",
        BORDER_THICK: "1",
        FONT_SIZE: "7",
        BACKGROUND_COLOR: "white",
        PROPERTY: "Input",
    },
}

export default Constant;